service: backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  keywordsApi:
    handler: handlers/keywords-handler.handler
    events:
      - httpApi:
          path: /getKeywords
          method: post
    environment: ${file(env.json)}
  googleSearchApi:
    handler: handlers/search-handler.handler
    events:
      - httpApi:
          path: /getSearchResults
          method: post
  selectionApi:
    handler: handlers/selection-handler.handler
    events:
      - httpApi:
          path: /getSelection
          method: post
    environment: ${file(env.json)}

plugins:
  - serverless-offline
