service: backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  keywordsApi:
    handler: handlers/gpt-handler.handler
    events:
      - httpApi:
          path: /
          method: post
    environment: ${file(env.json)}
  googleSearchApi:
    handler: handlers/search-handle.handler
    events:
      - httpApi:
          path: /scrape
          method: post

plugins:
  - serverless-offline
