service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: gpt-handler.handler
    events:
      - httpApi:
          path: /
          method: post
    environment: ${file(env.json)}
  # scraperAPI:
  #   handler: web-scraper-handler.handler
  #   events:
  #     - httpApi:
  #         path: /
  #         method: post

plugins:
  - serverless-offline
